
# KITCHEN_TRAINING __________________________________________________

dresser_covaro:
  model: dresser_covaro
  model_type: urdf
  position: [0, -1.975, 0]
  orientation: [0, 0, 1.570796327]

dresser_louis:
  model: dresser_louis
  model_type: urdf
  position: [-1.30, 0.10, 0]
  orientation: [0, 0, 0]

counter:
  model: counter
  model_type: urdf
  position: [1.8, -0.3, 0]
  orientation: [0, 0, 0]

wooden_plank:
  model: wooden_plank
  model_type: urdf
  position: [1.7, -0.570, 0.95]
  orientation: [0, 0, 0]

milk:
  model: milk
  model_type: urdf
  position: [-1.20, 0, 0.8]
  orientation: [0, 0, 0]

# LIVING ROOM__________________________________________________

# BEDROOM_____________________________________________________________

# FLOOR______________________________________________________________


