bb:
 position:
  x: -1.19531059265
  y: -0.0171677786857
  z: 0.7028403758999999
 orientation:
  x: 0.0
  y: 0.0
  z: -0.000404297577916
  w: 0.999999940395
 lwh:
  x: 0.03394824116455
  y: 0.04935763372755
  z: 0.234755182266
